//Add by xxfan

enum
{
    P2P_NEW_ENDPOINT_FAILED= 1,
    P2P_ENDPOINT_REGISTER_FAILED=2,
    P2P_ENDPOINT_REGISTER_TIMEOUT=3,
    P2P_CONNECTION_FAILED=4,
    FSP_OPEN_FILE_FAILED=5,
    FSP_OPEN_DIR_FAILED=6,
    FSP_GET_FILE_FAILED=7,
    FSP_READ_FILE_FAILED=8,
    FILE_NOT_EXISTED=9,
    FILE_OPEN_FAILED=10,
    MISS_PARAMETER_VALUE=11,
    P2P_INIT_FAILED=12,
};
//#define FSP_CC_ERR          84    /* error response from server.          */

