//Add by xxfan

enum
{
    P2P_NEW_ENDPOINT_FAILED= 1,
    P2P_ENDPOINT_REGISTER_FAILED,
    P2P_ENDPOINT_REGISTER_TIMEOUT,
    P2P_CONNECTION_FAILED,
    FSP_OPEN_FILE_FAILED,
    FSP_OPEN_DIR_FAILED,
    FSP_GET_FILE_FAILED,
    FSP_READ_FILE_FAILED,
    FILE_NOT_EXITED,
    FILE_OPEN_FAILED,
    MISS_PARAMETER_VALUE
};

